import type { DesignRationale } from "@/types/design";
import type { RationaleContext } from "@/lib/integrations/gemini";
import dataset from "@/data/reonic-training-dataset.json";

interface DataRow {
  objectiveHint: string;
  features: {
    annualConsumptionKwh: number;
    electricityPrice: number;
    hasEv: boolean;
    heatingType: string;
    householdSize: number;
    hasHeatPump: boolean;
  };
}

const ROWS = dataset as DataRow[];

function distance(row: DataRow, ctx: RationaleContext): number {
  const demand = Math.abs(row.features.annualConsumptionKwh - ctx.profile.annualConsumption) / 12000;
  const price = Math.abs(row.features.electricityPrice - ctx.profile.electricityPrice) / 0.5;
  const ev = row.features.hasEv === ctx.profile.hasEV ? 0 : 0.4;
  const heating = row.features.heatingType === ctx.profile.heatingType ? 0 : 0.8;
  const size = Math.abs(row.features.householdSize - ctx.profile.householdSize) / 6;
  const priority = row.objectiveHint === ctx.priority ? 0 : 0.35;
  return demand + price + ev + heating + size + priority;
}

export function generateLocalModelRationale(context: RationaleContext): DesignRationale {
  const nearest = [...ROWS].sort((a, b) => distance(a, context) - distance(b, context))[0];
  const objective =
    context.priority === "maximize_savings"
      ? "maximize annual bill reduction"
      : context.priority === "minimize_upfront"
        ? "reduce upfront investment"
        : "maximize on-site solar usage";
  const similarity = nearest ? (1 / (0.15 + distance(nearest, context))).toFixed(2) : "n/a";

  return {
    pvReason: `${context.recommendation.pvSizeKw} kWp is selected based on matched historical projects and current roof/module constraints (${context.recommendation.estimatedModuleCount} modules).`,
    batteryReason: `${context.recommendation.batteryKwh} kWh aligns with the ${objective} objective while targeting ${context.recommendation.estimatedSelfConsumptionPct}% self-consumption.`,
    heatPumpReason: context.recommendation.recommendHeatPump
      ? "Heat pump is recommended because matched historical cases with similar demand/heating profiles showed strong decarbonization value."
      : "Heat pump is not recommended in this variant because matched cases under this objective prioritized other investments first.",
    tradeoffSummary: `Local trained fallback model selected this rationale from nearest-neighbor patterning (similarity score ${similarity}). Projected CAPEX EUR ${context.financials.installCost}, annual savings EUR ${context.financials.annualSavings}, payback ${context.financials.paybackYears} years.`,
    assumptions: [
      "Generated by local trained fallback model (Reonic-derived dataset).",
      "All numeric values are grounded in deterministic recommendation and financial outputs.",
    ],
  };
}
